import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="flex flex-col min-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full md:max-w-screen-sm mx-auto mt-4">
        <h1 className="text-3xl font-bold underline">Hello world!</h1>

        <div className="home__container flex flex-col justify-between h-auto md:h-full border-2 border-gray-800 rounded-lg bg-orange-100 px-4 py-6 md:px-6">
          <div>
            <h3 className="leading-tight">Are you safe?</h3>
            <p className="pt-1 leading-snug">
              Basic protective measures against the new coronavirus
            </p>
          </div>
          <div>
            <button className="btn w-auto border-2 border-gray-800 bg-white hover:bg-gray-900 hover:text-white focus:text-white focus:bg-gray-900 button-xl mt-4 md:mt-5">
              Take the Quiz
            </button>
          </div>
        </div>
      </main>

      <footer className="bg-white w-full border-t mt-auto py-2 text-center">
        <a href="./" target="_blank" rel="noopener noreferrer">
          Ultra Pulse
        </a>
      </footer>
    </div>
  );
}
